<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Model;

use BeanstreamModule\Model\Base\BeanstreamPayment as BaseBeanstreamPayment;

/**
 * Class BeanstreamPayment
 * @package BeanstreamModule\Model
 */
class BeanstreamPayment extends BaseBeanstreamPayment
{
}
