<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Action;

use BeanstreamModule\Action\Base\BeanstreamPaymentAction as  BaseBeanstreamPaymentAction;

/**
 * Class BeanstreamPaymentAction
 * @package BeanstreamModule\Action
 */
class BeanstreamPaymentAction extends BaseBeanstreamPaymentAction
{
}
