<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Form\Type;

use BeanstreamModule\Form\Type\Base\BeanstreamPaymentIdType as BaseBeanstreamPaymentIdType;

/**
 * Class BeanstreamPayment
 * @package BeanstreamModule\Form
 */
class BeanstreamPaymentIdType extends BaseBeanstreamPaymentIdType
{
}
