<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event\Module\Base;

/**
 * Class BeanstreamModuleEvents
 * @package BeanstreamModule\Event\Module\Base
 * @author TheliaStudio
 */
class BeanstreamModuleEvents
{
    const BEANSTREAM_PAYMENT_CREATE = "action.beanstream_payment.create";
    const BEANSTREAM_PAYMENT_UPDATE = "action.beanstream_payment.update";
    const BEANSTREAM_PAYMENT_DELETE = "action.beanstream_payment.delete";
}
