<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event;

use BeanstreamModule\Event\Base\BeanstreamPaymentEvents as BaseBeanstreamPaymentEvents;

/**
 * Class BeanstreamPaymentEvents
 * @package BeanstreamModule\Event
 */
class BeanstreamPaymentEvents extends BaseBeanstreamPaymentEvents
{
}
