<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event;

use BeanstreamModule\Event\Base\BeanstreamModuleEvents as BaseBeanstreamModuleEvents;

/**
 * Class BeanstreamModuleEvents
 * @package BeanstreamModule\Event
 * @author TheliaStudio
 */
class BeanstreamModuleEvents extends BaseBeanstreamModuleEvents
{
}
