<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event;

use BeanstreamModule\Event\Base\BeanstreamPaymentEvent as BaseBeanstreamPaymentEvent;

/**
 * Class BeanstreamPaymentEvent
 * @package BeanstreamModule\Event
 */
class BeanstreamPaymentEvent extends BaseBeanstreamPaymentEvent
{
}
