<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Form\Base;

use BeanstreamModule\Form\BeanstreamPaymentCreateForm as ChildBeanstreamPaymentCreateForm;
use BeanstreamModule\Form\Type\BeanstreamPaymentIdType;

/**
 * Class BeanstreamPaymentForm
 * @package BeanstreamModule\Form
 * @author TheliaStudio
 */
class BeanstreamPaymentUpdateForm extends ChildBeanstreamPaymentCreateForm
{
    const FORM_NAME = "beanstream_payment_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", BeanstreamPaymentIdType::TYPE_NAME)
        ;
    }
}
