<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Loop;

use BeanstreamModule\Loop\Base\BeanstreamPayment as BaseBeanstreamPaymentLoop;

/**
 * Class BeanstreamPayment
 * @package BeanstreamModule\Loop
 */
class BeanstreamPayment extends BaseBeanstreamPaymentLoop
{
    /**
     * You may now add your own logic
     */
}
