<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Form;

use BeanstreamModule\Form\Base\BeanstreamPaymentCreateForm as BaseBeanstreamPaymentCreateForm;

/**
 * Class BeanstreamPaymentCreateForm
 * @package BeanstreamModule\Form
 */
class BeanstreamPaymentCreateForm extends BaseBeanstreamPaymentCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "order_id" => "Order id",
            "message_id" => "Message id",
            "message" => "Message",
        );
    }
}
