<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event\Module;

use BeanstreamModule\Event\Module\Base\BeanstreamModuleEvents as BaseBeanstreamModuleEvents;

/**
 * Class BeanstreamModuleEvents
 * @package BeanstreamModule\Event\Module
 * @author TheliaStudio
 */
class BeanstreamModuleEvents extends BaseBeanstreamModuleEvents
{
}
