<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Controller\Base;

use BeanstreamModule\BeanstreamModule;
use Thelia\Controller\Admin\BaseAdminController;
use Thelia\Form\Exception\FormValidationException;
use BeanstreamModule\Model\Config\BeanstreamModuleConfigValue;

/**
 * Class BeanstreamModuleConfigController
 * @package BeanstreamModule\Controller\Base
 * @author TheliaStudio
 */
class BeanstreamModuleConfigController extends BaseAdminController
{
    public function defaultAction()
    {
        return $this->render("beanstreammodule-configuration");
    }

    public function saveAction()
    {
        $baseForm = $this->createForm("beanstreammodule.configuration");

        $errorMessage = null;

        try {
            $form = $this->validateForm($baseForm);
            $data = $form->getData();

            BeanstreamModule::setConfigValue(BeanstreamModuleConfigValue::MERCHANT_ID, is_bool($data["merchant_id"]) ? (int) ($data["merchant_id"]) : $data["merchant_id"]);
            BeanstreamModule::setConfigValue(BeanstreamModuleConfigValue::PASSCODE, is_bool($data["passcode"]) ? (int) ($data["passcode"]) : $data["passcode"]);
        } catch (FormValidationException $ex) {
            // Invalid data entered
            $errorMessage = $this->createStandardFormValidationErrorMessage($ex);
        } catch (\Exception $ex) {
            // Any other error
            $errorMessage = $this->getTranslator()->trans('Sorry, an error occurred: %err', ['%err' => $ex->getMessage()], [], BeanstreamModule::MESSAGE_DOMAIN);
        }

        if (null !== $errorMessage) {
            // Mark the form as with error
            $baseForm->setErrorMessage($errorMessage);

            // Send the form and the error to the parser
            $this->getParserContext()
                ->addForm($baseForm)
                ->setGeneralError($errorMessage)
            ;
        } else {
            $this->getParserContext()
                ->set("success", true)
            ;
        }

        return $this->defaultAction();
    }
}
