<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event\Base;

use BeanstreamModule\Event\Module\BeanstreamModuleEvents as ChildBeanstreamModuleEvents;

/*
 * Class BeanstreamPaymentEvents
 * @package BeanstreamModule\Event\Base
 * @author TheliaStudio
 */
class BeanstreamPaymentEvents
{
    const CREATE = ChildBeanstreamModuleEvents::BEANSTREAM_PAYMENT_CREATE;
    const UPDATE = ChildBeanstreamModuleEvents::BEANSTREAM_PAYMENT_UPDATE;
    const DELETE = ChildBeanstreamModuleEvents::BEANSTREAM_PAYMENT_DELETE;
}
