<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event\Base;

/**
 * Class BeanstreamModuleEvents
 * @package BeanstreamModule\Event\Base
 * @author TheliaStudio
 */
class BeanstreamModuleEvents
{
}
