<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Event\Base;

use Thelia\Core\Event\ActionEvent;
use BeanstreamModule\Model\BeanstreamPayment;

/**
* Class BeanstreamPaymentEvent
* @package BeanstreamModule\Event\Base
* @author TheliaStudio
*/
class BeanstreamPaymentEvent extends ActionEvent
{
    protected $id;
    protected $orderId;
    protected $messageId;
    protected $message;
    protected $beanstreamPayment;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getOrderId()
    {
        return $this->orderId;
    }

    public function setOrderId($orderId)
    {
        $this->orderId = $orderId;

        return $this;
    }

    public function getMessageId()
    {
        return $this->messageId;
    }

    public function setMessageId($messageId)
    {
        $this->messageId = $messageId;

        return $this;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($message)
    {
        $this->message = $message;

        return $this;
    }

    public function getBeanstreamPayment()
    {
        return $this->beanstreamPayment;
    }

    public function setBeanstreamPayment(BeanstreamPayment $beanstreamPayment)
    {
        $this->beanstreamPayment = $beanstreamPayment;

        return $this;
    }
}
