<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use BeanstreamModule\Model\BeanstreamPaymentQuery;

/**
 * Class BeanstreamPayment
 * @package BeanstreamModule\Form\Base
 * @author TheliaStudio
 */
class BeanstreamPaymentIdType extends AbstractIdType
{
    const TYPE_NAME = "beanstream_payment_id";

    protected function getQuery()
    {
        return new BeanstreamPaymentQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
