<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace BeanstreamModule\Controller;

use BeanstreamModule\Controller\Base\BeanstreamModuleConfigController as BaseBeanstreamModuleConfigController;

/**
 * Class BeanstreamModuleConfigController
 * @package BeanstreamModule\Controller
 */
class BeanstreamModuleConfigController extends BaseBeanstreamModuleConfigController
{
}
